In [8]:
import numpy as np
# initialize arrays from nested list
a = np.array([1,2,3])
print(type(a))
print a.shape


b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0][0], b[0][1], b[0][2])
print(b[0,0], b[0,1], b[0,2])

<type 'numpy.ndarray'>
(3,)
(2, 3)
(1, 2, 3)
(1, 2, 3)


In [21]:
a = np.zeros((2,2))
print(a)

b = np.ones((1,2))
print(b.shape)

c = np.full((2,2), 7)
print(c)

d = np.eye(3)
print(d)

e = np.random.random((2,2))
print (e)

d = np.empty((4,4))
print d

[[ 0.  0.]
 [ 0.  0.]]
(1, 2)
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.09693418  0.63322655]
 [ 0.81134955  0.84715623]]
[[  6.92657486e-310   6.92657486e-310   6.92657486e-310   6.92657486e-310]
 [  1.85002051e-316   4.94065646e-324   1.91108149e-316   1.91108189e-316]
 [  0.00000000e+000   6.92655525e-310   6.35862486e-321   0.00000000e+000]
 [  4.74303020e-322   1.58101007e-322   1.85001340e-316   6.92655525e-310]]


In [23]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

row_r1 = a[1,:]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)


col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)


(array([5, 6, 7, 8]), (4,))
(array([[5, 6, 7, 8]]), (1, 4))
(array([ 2,  6, 10]), (3,))
(array([[ 2],
       [ 6],
       [10]]), (3, 1))


In [24]:
a = np.array([[1,2],[3,4],[5,6]])


print(a[[0,1,2],[0,1,0]])

print(np.array([a[0,0], a[1,1], a[2,0]]))

print(a[[0,0], [1,1]])

print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [27]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(a)

b = np.array([0,2,0,1])
print(a[np.arange(4),b])

a[np.arange(4),b]+=10
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [32]:
# boolean array indexing
a = np.array([[1,2],[3,4],[5,6]])
bool_index = a>2
print bool_index

print(a[bool_index])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [35]:
#datatype
x = np.array([1,2])

print(x.dtype)

x = np.array([1.0])
print x.dtype

x = np.array([1,2], dtype=np.int64)
print x.dtype

int64
float64
int64


In [37]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(x - y)
print(x * y)

print(x/y)

print(np.sqrt(x))

[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [42]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))

print(x.dot(v))
print(v.dot(x))


print(x.dot(y))

219
219
[29 67]
[39 58]
[[19 22]
 [43 50]]


In [43]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x,axis=0))

10
[4 6]


In [45]:
x = np.array([[1,2],[3,4]])
print(x)
print(x.T)

v = np.array([1,2,3])
print(v.T)

v = np.array([[1,2,3]])
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[[1]
 [2]
 [3]]


In [49]:
# boradcasting
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([[1,0,1]])
y = np.empty_like(x)

y = x +v
print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [63]:
v = np.array([1,2,3])
w = np.array([4,5])

n = np.reshape(v,(3,1))
print n
print(np.reshape(v,(3,1))*w)

x = np.array([[1,2,3],[4,5,6]])
print x+v

print((x.T+w).T)

print(x + np.reshape(w,(2,1)))

print x*2

[[1]
 [2]
 [3]]
[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
